### ISSUE TITLE
Exception upon closing transport-websocket

### ISSUE THREAD

**Issue by Khazul** [RoonLabs/node-roon-api#16]
```
*** Uncaught Exception:
RollingLog.js:28
*** Message: this.moo.close is not a function
RollingLog.js:36
*** Stack: TypeError: this.moo.close is not a function
RollingLog.js:40
    at Transport.close (D:\GitHub\roon-extension-deep-harmony\node_modules\node-roon-api\transport-websocket.js:47:18)
    at WebSocket.Transport.ws.onclose (D:\GitHub\roon-extension-deep-harmony\node_modules\node-roon-api\transport-websocket.js:18:14)
    at WebSocket.onClose (D:\GitHub\roon-extension-deep-harmony\node_modules\node-roon-api\node_modules\ws\lib\WebSocket.js:446:14)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.cleanupWebsocketResources (D:\GitHub\roon-extension-deep-harmony\node_modules\node-roon-api\node_modules\ws\lib\WebSocket.js:950:8)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

in Transport.close (node-roon-api\transport-websocket.js:47:18), there is a call to moo.close() which does not appear to exist.

The simple way to reproduce this enable an extension, then perform an action that will unpair the extension and close its socket, for example, in Roon UI settings, > extension settings, click [View], select an extension and remove it.

**Comment by dannyfiresnake** [comment]
fixed 0262566
