### ISSUE TITLE
Update of ws dependency broke compatibility with node 6.x and 7.x

### ISSUE THREAD

**Issue by JanKoudijs** [RoonLabs/node-roon-api#18]
The [recent update](https://github.com/RoonLabs/node-roon-api/commit/4eb0b63d0c8a6d3d2957eecc9836e0fb8e666d86) of the ws dependency breaks compatibility with node 6.x and 7.x. The [ws change log](https://github.com/websockets/ws/releases/tag/7.0.0) shows that node 6 support was dropped in ws v7.0.0.

An exception is thrown at startup:

```
/home/Jan/.RoonExtensions/lib/node_modules/roon-extension-manager/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Jan/.RoonExtensions/lib/node_modules/roon-extension-manager/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:570:32)
```

Assuming that dropping compatibility wasn't intentional and knowing that the vulnerability was already solved in version 3.3.1 it might be enough to stick to ws 3.x. I verified that node 6.9.5 is working again (no exception thrown) by using:

    "ws": "^3.3.1"

**Comment by dannyfiresnake** [comment]
this is very old... im not sure what's the story today, but supporting ancient versions of nodejs is not interesting.
